version: '3.8'

services:
  # PostgreSQL untuk development
  postgres:
    image: postgres:16-alpine
    container_name: selsila-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=selsila_airdrop
      - POSTGRES_USER=selsila
      - POSTGRES_PASSWORD=selsiladb
      - POSTGRES_MAX_CONNECTIONS=50
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U selsila"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis untuk development
  redis:
    image: redis:7-alpine
    container_name: selsila-redis-dev
    ports:
      - "6379:6379"
    command: 
      - redis-server
      - --requirepass selsilaredis
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  default:
    driver: bridge